added `Open` method to each menu type
roflmuffin/CounterStrikeSharp pull request #385
Opened 2024-03-19 01:32 UTC by partiusfabaa

```cs
var menu = new ChatMenu("Test");
menu.AddMenuOption("test", (controller, option) => {});
menu.Open(player);
```

```cs
var menu = new ConsoleMenu("Test");
menu.AddMenuOption("test", (controller, option) => {});
menu.Open(player);
```

```cs
var menu = new CenterHtmlMenu("Test", this);
menu.AddMenuOption("test", (controller, option) => {});
menu.Open(player);
```

2024-03-25 07:49 UTC, B3none reviewed
I think it's worth having the player value nullable for the `Open` function then fall back to opening the menu for every player returned by `Utilities.GetPlayers()`, what do you think?

2024-03-25 08:10 UTC, partiusfabaa commented
> I think it's worth having the player value nullable for the `Open` function then fall back to opening the menu for every player returned by `Utilities.GetPlayers()`, what do you think?

I think it would be better to make a separate method ala `OpenToAll` and it will be more intuitive for people

2024-03-25 08:39 UTC, B3none requested changes

2024-03-25 08:39 UTC, B3none commented on managed/CounterStrikeSharp.API/Modules/Menu/BaseMenu.cs
> +        foreach (var players in Utilities.GetPlayers())
This should be `var player in Utilities.GetPlayers()`

2024-03-25 08:50 UTC, roflmuffin commented
I don't think the menu instance itself should include any logic for opening menus for a given player, since this is handled by the menu manager. I think it would be better to implement these as extension methods for both `CCSPlayerController` and `IMenu`. The problem is that the HTML menu requires context to a BasePlugin while the other menus do not. In any case, I don't think the change to require a `BasePlugin` from the constructor of `CenterHtmlMenu` is a good change.

2024-03-25 10:38 UTC, Iksix commented
It's a good idea.

2024-03-26 02:57 UTC, Muinez commented
> I don't think the menu instance itself should include any logic for opening menus for a given player, since this is handled by the menu manager. I think it would be better to implement these as extension methods for both `CCSPlayerController` and `IMenu`. The problem is that the HTML menu requires context to a BasePlugin while the other menus do not. In any case, I don't think the change to require a `BasePlugin` from the constructor of `CenterHtmlMenu` is a good change.

I think it's better than having a MenuManager because you can get confused and call the wrong method, having 1 single method Open simplifies the work because you don't have to think about which method to call, also the fact that HtmlMenu's BasePlugin is passed in the constructor and not at opening simplifies the work, let's say you can create a class that creates a menu with a specific Title and that returns an IMenu, with the current implementation to open a menu you have to know its type.

2024-04-01 08:03 UTC, roflmuffin approved these changes

2024-04-01 08:04 UTC, merged